# Test script for inspecting the entity graph generated by entity_graph.py
"""
Checks entity_graph.json after a run of entity_graph.py: prints
node/edge counts and expands context around one sample entity to confirm
alerts are being linked together (not just parsed in isolation).

Run: python graph/inspect_graph.py
"""
# DefaultDict creates missing keys, so we can count nodes by type without predefining them.
from collections import defaultdict

from entity_graph import GRAPH_PATH, load_graph, summarize_context

# Sample entity to inspect in the graph. Inspect the user named "npetrova" in the graph to 
# see its context and connections. Change this to another entity type and value. 
SAMPLE_ENTITY = ("user", "npetrova")


def main():
    graph = load_graph()    
    # Create a dictionary to count the number of nodes by their type in the graph.
    nodes_by_type = defaultdict(int)
    for _, attrs in graph.nodes(data=True):
        nodes_by_type[attrs["type"]] += 1

    print(f"Loaded {GRAPH_PATH}: {graph.number_of_nodes()} nodes, {graph.number_of_edges()} edges.")
    print(f"Nodes by type: {dict(nodes_by_type)}")

    entity_type, value = SAMPLE_ENTITY
    print(f"\n{summarize_context(graph, entity_type, value, hops=2)}")


if __name__ == "__main__":
    main()
