apiVersion: v1
kind: Service
metadata:
  name: meridian-triage-api
  namespace: meridian
spec:
  type: LoadBalancer
  selector:
    app: meridian-triage-api
  ports:
    - port: 80
      targetPort: 8000
